parser: '@typescript-eslint/parser'
root: true
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
rules:
  semi: error
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/ban-ts-comment': off

overrides:
  - files: '*.config.js'
    env:
      node: true
    rules:
      '@typescript-eslint/no-var-requires': off
